
timeout: 1200s
steps:
  # build container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/civiqa-301113/openstates-scrapers", "-f", "Dockerfile", "."]

#   # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/civiqa-301113/openstates-scrapers"]
